---
title: "SVM Model"
output: html_notebook
---
```{r setup}
library(knitr)
knitr::knit_hooks$set(time_it = local({
 now <- NULL
 function(before, options) {
   if (before) {
     now <<- Sys.time()
   } else {
     res <- difftime(Sys.time(), now, units = "secs")
     paste("Time for this chunk:", round(res, 2), "seconds")
   }
 }
}))
knitr::opts_chunk$set(time_it = TRUE)

#knitr::opts_knit$set(root.dir = "C:/Users/Jim/Documents/Project/STAT-472-Project/Data Frame")
knitr::opts_knit$set(root.dir = "D:/School/School Work/2025-2026/2026/STAT 472/STAT-472-Project/Data Frame")

```


```{r}
library(e1071)
library(dplyr)
library(caret)
library(doParallel)
library(ggplot2)

```


```{r}
data <- read.csv("filtered_timeseries_fifa_players.csv")
var <- read.csv("variables.csv")
temp <- read.csv("defenders.csv")

var <- as.character(unlist(var))
df <- data %>% select(all_of(var), value_eur, club_name, year) %>% na.omit()
df$value_eur <- log(df$value_eur)
#df <- temp %>% select(all_of(var), 5) %>% na.omit()

```


```{r}
set.seed(123)

train_index <- createDataPartition(df$value_eur, p = 0.7, list = FALSE)
train <- df[train_index, ]
test  <- df[-train_index, ]
team_train <- train$club_name
team_test <- test$club_name
year_train <- train$year
year_test <- test$year

```


```{r}
preproc <- preProcess(train %>% select(-value_eur, -club_name, -year), method = c("center", "scale"))

train_scaled <- predict(preproc, train %>% select(-value_eur, -club_name, -year))
test_scaled  <- predict(preproc, test %>% select(-value_eur, -club_name, -year))
train_scaled$value_eur <- train$value_eur
test_scaled$value_eur  <- test$value_eur

```


```{r}
svm_model <- svm(
  value_eur ~ .,
  data = train_scaled,
  type = "eps-regression",
  kernel = "radial"
)

```


```{r}
preds <- predict(svm_model, test_scaled)

```


```{r}
# rmse <- sqrt(mean((preds - test_scaled$value_eur)^2))
# mae  <- mean(abs(preds - test_scaled$value_eur))
# 
# rmse
# mae
# R2(preds, test_scaled$value_eur)

postResample(pred = preds, obs = test_scaled$value_eur)

```


```{r}
cl <- makeCluster(parallel::detectCores() - 1)
registerDoParallel(cl)

```


```{r}
ctrl <- trainControl(
  method = "cv",
  number = 3,
  search = "random"
)

```


```{r}
# svm_grid <- expand.grid(
#   sigma = c(0.001, 0.01, 0.1),
#   C = c(0.1, 1, 10, 50)
# )

svm_grid <- expand.grid(
  sigma = c(0.01, 0.1),
  C = c(1, 10)
)

```


```{r}
# svm_tuned <- train(
#   value_eur ~ .,
#   data = train_scaled,
#   method = "svmRadial",
#   trControl = ctrl,
#   tuneGrid = svm_grid,
#   metric = "RMSE"
# )

svm_tuned <- train(
  value_eur ~ .,
  data = train_scaled,
  method = "svmRadial",
  trControl = ctrl,
  tuneLength = 5   # tries 5 random combos
)

```


```{r}
stopCluster(cl)
```


```{r}
svm_tuned$bestTune

```


```{r}
cl <- makeCluster(parallel::detectCores() - 1)
registerDoParallel(cl)

```


```{r}
final_model <- svm(
  value_eur ~ .,
  data = train_scaled,
  kernel = "radial",
  cost = svm_tuned$bestTune$C,
  gamma = svm_tuned$bestTune$sigma
)

stopCluster(cl)

```


```{r}
preds <- predict(final_model, test_scaled)

# rmse_tuned <- sqrt(mean((preds - test_scaled$value_eur)^2))
# mae_tuned  <- mean(abs(preds - test_scaled$value_eur))
# 
# 
# rmse_tuned
# mae_tuned
# R2(preds_tuned, test_scaled$value_eur)

postResample(pred = preds, obs = test_scaled$value_eur)

```


```{r}
df_plot <- data.frame(
  Actual = test_scaled$value_eur,
  Predicted = preds
)

r2 <- cor(df_plot$Actual, df_plot$Predicted)^2

ggplot(df_plot, aes(x = Actual, y = Predicted)) +
  geom_point(color = "steelblue",alpha = 0.5) +
  geom_abline(intercept = 0, slope = 1, color = "red", linewidth = 1) +
  annotate("text", x = min(df_plot$Actual), y = max(df_plot$Predicted),
           label = paste("R² =", round(r2, 3)),
           hjust = 0, size = 5) +
  labs(
    title = "Predicted vs Actual Value (SVM)",
    x = "Actual Value",
    y = "Predicted Value"
  ) +
  theme_minimal()

```


```{r}
residuals <- test_scaled$value_eur - preds

df_res <- data.frame(
  Year = year_test,
  Team = team_test,
  Predicted = preds,
  Actual = test_scaled$value_eur,
  Residuals = residuals
)

qq_data <- data.frame(residuals = residuals)

ggplot(df_res, aes(x = Predicted, y = Residuals)) +
  geom_point(color = "steelblue",alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(
    title = "Residuals vs Predicted",
    x = "Predicted Values",
    y = "Residuals"
  ) +
  theme_minimal()

ggplot(qq_data, aes(sample = residuals)) +
  stat_qq(color = "steelblue", alpha = 0.5) +
  stat_qq_line(color = "red", linewidth = 1) +
  labs(
    title = "QQ Plot of Residuals",
    x = "Theoretical Quantiles",
    y = "Sample Quantiles"
  ) +
  theme_minimal()

ggplot(df_res, aes(x = Residuals)) +
  geom_histogram(fill = "steelblue",bins = 30) +
  labs(
    title = "Residual Distribution",
    x = "Residual",
    y = "Count"
  ) +
  theme_minimal()

ggplot(df_res, aes(x = Actual, y = Residuals)) +
  geom_point(color = "steelblue",alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(
    title = "Residuals vs Actual",
    x = "Actual Values",
    y = "Residuals"
  ) +
  theme_minimal()

df_res$abs_error <- abs(df_res$Residuals)

worst <- df_res[order(-df_res$abs_error), ][1:10, ]
worst
```


```{r}
importance <- varImp(svm_tuned, scale = TRUE)
importance_df <- data.frame(
  Feature = rownames(importance$importance),
  Importance = importance$importance$Overall
)

importance_df <- importance_df[order(importance_df$Importance, decreasing = TRUE), ]

top_n <- 25
importance_top <- head(importance_df, top_n)

ggplot(importance_df, aes(x = reorder(Feature, Importance), y = Importance, fill = Importance)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_gradient(low = "lightgreen", high = "darkgreen") +
  labs(
    title = "Feature Importance (SVM Model)",
    x = "Feature",
    y = "Importance"
  ) +
  theme_minimal()

ggplot(importance_top, aes(x = reorder(Feature, Importance), y = Importance, fill = Importance)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_gradient(low = "lightblue", high = "darkblue") +
  labs(
    title = "Top 25 Feature Importance (SVM Model)",
    x = "Feature",
    y = "Importance"
  ) +
  #theme_minimal(base_size = 14) +
  theme(legend.position = "none")
```


```{r}
team_residuals <- df_res %>%
  group_by(Team) %>%
  summarise(
    Mean_Residual = mean(Residuals),
    Acutal = mean(exp(Actual)),
    Predicted = mean(exp(Predicted)),
    MAE = mean(abs(Residuals)),
    RMSE = sqrt(mean(Residuals^2)),
    Count = n()) %>%
  filter(Count >= 10) %>%
  arrange(desc(Mean_Residual))

team_residuals
```


```{r}
rapids_residuals <- df_res %>%
  filter(Team == "Colorado Rapids") %>%
  group_by(Year) %>%
  summarise(
    Mean_Residual = mean(Residuals)
    ) %>%
  arrange(Year)

rapids_score <- data.frame(
  Year = c(2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022),
  Won = c(9, 15, 9, 8, 12, 8, 17, 11),
  Mean_Residual = c(-.35, -.15, -.1, -.04, .05, .02, .31, .37)
)

#rapids_score <- merge(rapids_score, rapids_residuals[, c("Year", "Mean_Residual")], by = "Year", all.x = TRUE)

rapids_score
```


```{r}
p <- ggplot(rapids_score, aes(x = Year)) + 
  geom_line(aes(y = Mean_Residual, color = "Avg Log Residual"), linewidth = 1) + 
  geom_point(aes(y = Mean_Residual, color = "Avg Log Residual") , size = 2) + 
  
  geom_line(aes(y = Won / 50, color = "Wins"), linewidth = 1) + 
  geom_point(aes(y = Won / 50, color = "Wins"), size = 2) + 
  
  scale_x_continuous(breaks = rapids_score$Year) +
  
  scale_y_continuous(
    name = "Average Log Residual (Efficiency)",
    sec.axis = sec_axis(~. * 30, name = "Number of Game Won")
    ) + 
  
  labs(
    title = "Colorado Rapids: Roster Efficiency vs. Total Wins (2015-2022)", 
    x = "Year", 
    color = "Legend"
    ) + 
  
  theme_minimal() + 
  theme(legend.position = "bottom")
p
```


```{r}
#ggsave("Residuals vs Wins.pdf", plot = p, width = 12, height = 8, units = "in", dpi = 600)
```

